In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"D:\AI Eng\Projects\RNN-Sentiment Analysis\data\IMDB Dataset.csv")

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.shape

(50000, 2)

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.shape

(49582, 2)

### Pre-processing

#### Removing URLs

In [12]:
import re # Regular Expressions
def remove_urls(text):
    text=re.sub(r"http\S+","",text)
    return text
df["review"]=df["review"].apply(remove_urls)

#### Removing Punctuations

In [13]:
def remove_punctuation(text):
    text=re.sub(r"[^A-Za-b0-9\s]","",text)
    return text
df["review"]=df["review"].apply(remove_punctuation)

#### Removing HTML

In [20]:
def removing_html(text):
    text=re.sub(r"<.>","",text)
    return text
df["review"]=df["review"].apply(removing_html)

In [21]:
df.head()

                                              review sentiment
0  O     a  a a a  1 O   b  T a  a   a a a  b b T...  positive
1  A    b b T     a  BBC a a  a  a     a     b b ...  positive
2  I   a a  a     a        a  a a a a a  T    b  ...  positive
3  Baa  a a  a  b Ja   a b      a a  a  b b T    ...  negative
4  P Ma L   T  M  a a    a M Ma   a  a ab a a T  ...  positive

#### Removing the Stopswords

In [19]:
!pip install nltk
import nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\dexter\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\dexter\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dexter\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\dexter\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\dexter\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 9.4 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 4.9 MB/s  0:00:00
Installing collected packages: nltk
Successfully installed nltk-3.9.4

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("punkt_tab")
# this all are modules

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dexter\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dexter\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dexter\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [27]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")
    for workd in tokens:
        if wor